AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template for Layers-Demo Application

Globals:
    Function:
        Timeout: 60

Resources:

    DeserializeDemoFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: LayersApp-DeserializeDemo
            Description: Layers App Deserialize Demo Function
            Role: arn:aws:iam::706374939365:role/MyLambdaRole
            CodeUri: deserialize-demo/
            Handler: main.lambda_handler
            Runtime: python3.7
            Environment:
              Variables:
                REGION: us-east-1

    ObjectPathDataDemoFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: LayersApp-ObjectPathDataDemo
            Description: Layers App Deserialize Demo Function
            Role: arn:aws:iam::706374939365:role/MyLambdaRole
            CodeUri: objectpath-data-demo/
            Handler: main.lambda_handler
            Runtime: python3.7
            Environment:
              Variables:
                REGION: us-east-1

    CDDemoLambda:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: lambda_function.lambda_handler
        Runtime: python3.6
        CodeUri: ./LambdaCode
        Description: 'Lambda function for CD Demo'
        MemorySize: 128
        Timeout: 30
        Role: 'arn:aws:iam::706374939365:role/MyLambdaRole'
        Events:
          getAZsAPI:
            Type: Api
            Properties:
              Path: /getazs
              Method: get
        Environment:
          Variables:
            REGION: us-east-1